# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Last commit

on:
  push:

  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@master
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Build files with Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci

    - run: npm run build

    - run: npm run build:docs

    - name: Add file(s) for commit
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f dist/floorplan.js

    - name: Commit changes
      id: can_commit
      run: |-
       commit_result=$(git commit -m "Add changes to dist and docs" -a | tr -d '\n' || true)
       echo "::set-output name=commit_result::$commit_result"

    - name: Nothing to commit
      if: contains(steps.can_commit.outputs.commit_result, 'nothing to commit')
      run: echo "No changes found (for both main code and docs). Skipping push."

    - name: Dump GitHub context
      run: echo $JSON
      env:
        JSON: ${{ toJSON(github) }}

    - name: Set target branch (when pull request merged)
      run: echo 'TARGET_BRANCH=${{ github.head_ref }}' >> $GITHUB_ENV
      if: github.event.pull_request.merged

    - name: Set target branch (when changes pushed)
      run: echo 'TARGET_BRANCH=${{ github.ref_name }}' >> $GITHUB_ENV
      if: (github.event_name == 'push')

    - name: Dump target branch
      run: echo ${{ env.TARGET_BRANCH }}

    - name: Push changes to target branch
      if: (contains(steps.can_commit.outputs.commit_result, 'nothing to commit') == false)
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ env.TARGET_BRANCH }}
