name: Test on Merge to Master

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Test
    uses: ./.github/workflows/common-build-test.yaml
    with:
      upload-artifacts: true
