name: Build on Push[master] and PR[master]

on:
  workflow_run:
    workflows:
      - validate-pr
    types:
      - completed

jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.DEPLOY_KEY_FOR_BUILDS }}
        fetch-depth: 0

    - name: Build files with Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci

    - run: npm run build

    - name: Validate build success
      run: |
        if [ ! -f "dist/floorplan.js" ]; then
          echo "Build failed: 'dist/floorplan.js' not found."
          exit 1
        fi

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: dist/
