name: Test on PR

on:
  pull_request:
    types: [opened, synchronize, reopened]
    
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ssh-key: ${{ secrets.DEPLOY_KEY_FOR_BUILDS }}
        fetch-depth: 0

    - name: Build files with Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci

    - run: npm run build

    - name: Run tests
      run: npm test
      env:
        CI: true

    - name: Publish test results
      if: always() # Publish results even if tests fail
      uses: actions/upload-test-results@v2
      with:
        path: test-results/junit.xml

    - name: Validate build success
      run: |
        if [ ! -f "dist/floorplan.js" ]; then
          echo "Build failed: 'dist/floorplan.js' not found."
          exit 1
        fi

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: dist/
