name: Validate Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check if workflows folder is modified
        id: check-workflows
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -q '^.github/workflows/'; then
            echo "workflows_modified=true" >> $GITHUB_ENV
          else
            echo "workflows_modified=false" >> $GITHUB_ENV
          fi

      - name: Add warning comment if workflows are modified
        if: env.workflows_modified == 'true'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "⚠️ Warning: This PR modifies workflow files in the `.github/workflows/` folder. Please ensure these changes are intentional and secure."
            })