name: Draft Release with Notes and Build Artifacts
on:
    push:
        tags:
            - "v*.*.*"
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install
              run: npm ci
            - name: Build
              run: npm run build
            - name: Release
              uses: softprops/action-gh-release@v2
              if: startsWith(github.ref, 'refs/tags/')
              with:
                draft: true
                prerelease: ${{ contains(github.ref, '-') }}
                generate_release_notes: true
                append_body: true
                files: dist/*.js